### PR TITLE
Fix difficulty change error #4

### PR DESCRIPTION
**Pull request by ivanhuay**
what occurred to me to solve the problem is to use the index of each block to validate the difficulty.

To verify that the difficulty change works, add a test that performs the mining operation 25 times

running the test with the previous version of the code breaks and returns the error that is mentioned in the issue

### CODE REVIEW

**Comment by seanjameshan** [comment]
Hey @ivanhuay, thanks again for the PR! 

I think `this.chain.size - 1` on the `get difficulty()` function should fix the issue. I ran it on your fork and it passed the test. Do you want to add it to ur PR? :)

**Comment by ivanhuay** [comment]
Using the function with `this.chain.size -1` only delays the problem
```javascript
  get difficulty(): number {
    return Math.round((this.chain.size - 1)/ 50) + 3;
  }
```
running the test on the master branch and mining 26 times gives the error again

```
../Dev/blockchain/coin-cli/src/Node.ts:35
                throw e;
                ^
Failed to add block: Invalid Chain Error: Invalid Block Error: Hash 000b16ea09d53796b722a6fba6605f423f4b53ac76a531bf91adc866233e7be4 does not meet difficulty 4
```
The problem is when a new block is added all the previous blocks are validated using the same difficulty
thath process start [here](https://github.com/seanjameshan/coin-cli/blob/704543e230cc1163d91d240a10c603dac5daf461/src/Blockchain.ts#L22):

```javascript
  set chain(chain: List<Block>) {
    try {
      this.shouldReplaceChain(chain);
      this._chain = chain;
    } catch (e) {
      throw e;
    }
  }
```
after running
```javascript
addBlock(block: Block) {
    try {
      this.isValidNextBlock(block, this.latestBlock);
      this.chain = this.chain.push(block);//this line!
    } catch (e) {
      throw `Failed to add block: ${e}`;
    }
  }
```
shouldReplaceChain validate all blocks from chain using the same difficulty using [isValidBlocks](https://github.com/seanjameshan/coin-cli/blob/704543e230cc1163d91d240a10c603dac5daf461/src/Blockchain.ts#L121)

#### a possible solution
in my pull request I use the function
```javascript
getIndexDifficulty(index: number) {
    return Math.round(index / 50) + 3;
  }
```
that uses the index of each block to get the complexity

**Comment by ivanhuay** [comment]
@seanjameshan As a detail above, the problem is to validate all the blocks with the same difficulty

**Comment by seanjameshan** [comment]
Thank you @ivanhuay !!

**Pull request merged**
